### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by maanaskarwa** [zishang520/socket.io#27]
Could you share some benchmarks and testing numbers if you have them please? I am considering using this in production and want to know if it is battle tested and production ready. Thanks!

**Comment by zishang520** [comment]
Sorry, none yet.

**Comment by maanaskarwa** [comment]
Okay. Do you think this would be suitable for ~700 concurrent users sending about 10 requests per second? Just trying to get a sense of whether I should use it in my project. Thank you.

**Comment by zishang520** [comment]
Sorry, I can't give a clear answer. Due to the lack of development of the client version, I tested 300 client links to send and receive messages on a single machine based on the browser without much problem: the CPU is i7-6700hq (notebook), and the CPU  The occupancy rate is between 13-25% (there are indeed many places in the code that can be optimized to reduce gc consumption), the memory is relatively stable, and there seems to be no memory leak. In summary, you can test the actual situation by yourself.
